frequency: 30
sensor_timeout: 0.2
two_d_mode: false

publish_tf: false
publish_acceleration: true

# =========================
# Frames
# =========================

map_frame: cirtesu_base_link
odom_frame: world_ned
base_link_frame: girona500/base_link
world_frame: world_ned

# =========================
# INPUT 0 — ArUco absolute pose
# =========================

pose0: /girona500/navigator/aruco_pose

pose0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]

pose0_differential: false
pose0_relative: false
pose0_queue_size: 20

pose0_rejection_threshold: 2.0

# =========================
# INPUT 1 — Odometry (Stonefish)
# =========================

odom0: /girona500/navigator/odometry
odom0_config: [false, false, true,
               true, true, true,
               true,  true,  true,
               true, true, true,
               false, false, false]

odom0_differential: false
odom0_relative: false
odom0_queue_size: 20
